## Data Cleaning

In [1]:
import numpy as np 
import pandas as pd

In [ ]:
# Reading Files
cpi = pd.read_excel("../data/raw/CPI.xlsx", header=2)
wpi = pd.read_excel("../data/raw/WPI.xlsx")

### CPI Cleaning

In [11]:
cpi.columns = ['Date', 'CPI', 'Food', 'Food_Bev', 'Tobacco', 'Clothing', 'Housing', 'Fuel', 'Misc']

In [13]:
cpi = cpi.iloc[1:]

In [ ]:
cpi.head()

In [15]:
cpi = cpi.reset_index(drop=True)

In [ ]:
cpi.head()

In [18]:
cpi['Date'] = pd.to_datetime(cpi['Date'])
cpi['Date'] = cpi['Date'].dt.date

In [20]:
cpi = cpi.iloc[:, :5]

In [22]:
cpi.head()

         Date   CPI  Food Food_Bev Tobacco
0  2011-01-01  89.5  93.5     92.3    82.4
1  2011-02-01  88.4  89.9     89.3    83.5
2  2011-03-01  88.4  88.9     88.6    85.1
3  2011-04-01  89.1  89.1     88.9    87.6
4  2011-05-01  89.8  89.7     89.5    88.8

In [25]:
# Convert types
cpi['Date'] = pd.to_datetime(cpi['Date'])

cpi['CPI'] = pd.to_numeric(cpi['CPI'])
cpi['Food'] = pd.to_numeric(cpi['Food'])
cpi['Food_Bev'] = pd.to_numeric(cpi['Food_Bev'])
cpi['Tobacco'] = pd.to_numeric(cpi['Tobacco'])

In [ ]:
cpi.info()

In [27]:
cpi = cpi[['Date', 'CPI']]

In [29]:
cpi.head()

        Date   CPI
0 2011-01-01  89.5
1 2011-02-01  88.4
2 2011-03-01  88.4
3 2011-04-01  89.1
4 2011-05-01  89.8

### WPI Cleaning

In [ ]:
wpi.head()

In [31]:
wpi = pd.read_excel("../data/raw/WPI.xlsx", header=3)

In [ ]:
wpi.head()

In [ ]:
wpi.columns

In [37]:
wpi = pd.read_excel("../data/raw/WPI.xlsx", skiprows=3)

In [ ]:
wpi.head()

In [39]:
wpi = wpi[wpi.iloc[:,0] != 'Weight=>']

In [ ]:
wpi.head()

In [42]:
wpi = wpi.iloc[:, :2]   # safest

In [43]:
wpi.head()

  Unnamed: 0    Unnamed: 1
0        NaN           NaN
1        NaN  Index Values
3   Jan-2012           NaN
4   Feb-2012           NaN
5   Mar-2012           NaN

In [44]:
wpi.columns = ['Date', 'WPI']

In [49]:
wpi = wpi.iloc[2:]

In [50]:
wpi = wpi.reset_index(drop=True)

In [51]:
wpi.head()

       Date    WPI
0  Jan-2012    NaN
1  Feb-2012    NaN
2  Mar-2012    NaN
3  Apr-2012  104.7
4  May-2012  105.3

In [52]:
wpi.info()

<class 'pandas.DataFrame'>
RangeIndex: 187 entries, 0 to 186
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    183 non-null    str
 1   WPI     167 non-null    object
dtypes: object(1), str(1)
memory usage: 3.1+ KB

In [53]:
wpi.count()

Date    183
WPI     167
dtype: int64

In [54]:
wpi['Date'] = pd.to_datetime(wpi['Date'], format='%b-%Y', errors='coerce')
wpi['WPI'] = pd.to_numeric(wpi['WPI'], errors='coerce')

In [55]:
wpi['WPI'] = wpi['WPI'].ffill()

In [ ]:
wpi.head()

In [57]:
wpi['WPI'] = wpi['WPI'].ffill().bfill()

In [59]:
wpi = wpi[wpi['Date'] >= '2012-04-01']

In [61]:
wpi = wpi.reset_index(drop=True)

In [63]:
cpi.head()
wpi.head()

        Date    WPI
0 2012-04-01  104.7
1 2012-05-01  105.3
2 2012-06-01  105.3
3 2012-07-01  106.2
4 2012-08-01  106.9

In [64]:
cpi.head()

        Date   CPI
2 2011-03-01  88.4
3 2011-04-01  89.1
4 2011-05-01  89.8
5 2011-06-01  90.6
6 2011-07-01  91.8

In [65]:
cpi = cpi[cpi['Date'] >= '2012-04-01']
cpi = cpi.reset_index(drop=True)

In [66]:
df = pd.merge(cpi, wpi, on='Date', how='inner')

In [67]:
df.to_csv("../data/processed/final_dataset.csv", index=False)