### feature_engineering.ipynb

In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv('../data/processed/final_dataset.csv')

In [8]:
df.columns = df.columns.str.strip().str.lower()
df['date'] = pd.to_datetime(df['date'])
df = df.sort_values('date')

In [11]:
df.head()

        date    cpi    wpi
0 2012-04-01   97.8  104.7
1 2012-05-01   98.6  105.3
2 2012-06-01   99.8  105.3
3 2012-07-01  101.1  106.2
4 2012-08-01  102.2  106.9

#### Time Features

In [19]:
df['month'] = df['date'].dt.month
df['year'] = df['date'].dt.year 
df['quarter'] = df['date'].dt.quarter

df[['date','month','year','quarter']].head()

        date  month  year  quarter
0 2012-04-01      4  2012        2
1 2012-05-01      5  2012        2
2 2012-06-01      6  2012        2
3 2012-07-01      7  2012        3
4 2012-08-01      8  2012        3

#### Lag Features

In [20]:
df['lag_1'] = df['cpi'].shift(1)
df['lag_2'] = df['cpi'].shift(2)
df['lag_3'] = df['cpi'].shift(3)
df['lag_6'] = df['cpi'].shift(6)
df['lag_12'] = df['cpi'].shift(12)

df[['cpi','lag_1','lag_2']].head(10)

     cpi  lag_1  lag_2
0   97.8    NaN    NaN
1   98.6   97.8    NaN
2   99.8   98.6   97.8
3  101.1   99.8   98.6
4  102.2  101.1   99.8
5  102.9  102.2  101.1
6  103.6  102.9  102.2
7  104.3  103.6  102.9
8  104.6  104.3  103.6
9  104.6  104.6  104.3

#### Rolling Features

In [21]:
df['rolling_mean_3'] = df['cpi'].rolling(3).mean()
df['rolling_std_3'] = df['cpi'].rolling(3).std()

df['rolling_mean_6'] = df['cpi'].rolling(6).mean()
df['rolling_std_6'] = df['cpi'].rolling(6).std()

#### Growth (Inflation %)

In [23]:
df['cpi_pct_change'] = df['cpi'].pct_change() * 100

df[['cpi','cpi_pct_change']].head()

     cpi  cpi_pct_change
0   97.8             NaN
1   98.6        0.817996
2   99.8        1.217039
3  101.1        1.302605
4  102.2        1.088032

#### Difference Feature

In [27]:
df['cpi_diff'] = df['cpi'].diff()
df['cpi_diff'].head()

0    NaN
1    0.8
2    1.2
3    1.3
4    1.1
Name: cpi_diff, dtype: float64

## WPI Features

In [35]:
df['wpi_pct_change'] = df['wpi'].pct_change() * 100
df['wpi_lag1'] = df['wpi'].shift(1)

In [36]:
df['trend_index'] = range(len(df))
df['cpi_wpi_diff'] = df['cpi'] - df['wpi']

In [37]:
df = df.dropna()

df.shape

(152, 21)

In [41]:
df.head()

,date,cpi,wpi,month,year,quarter,lag_1,lag_2,lag_3,lag_6,...,rolling_mean_3,rolling_std_3,rolling_mean_6,rolling_std_6,cpi_pct_change,cpi_diff,wpi_pct_change,wpi_lag1,trend_index,cpi_wpi_diff
13,2013-05-01,106.9,108.6,5,2013,2,106.1,105.5,105.3,104.3,...,106.166667,0.702377,105.500000,0.892188,0.754006,0.8,0.000000,108.6,1,-1.7
14,2013-06-01,109.3,110.1,6,2013,2,106.9,106.1,105.5,104.6,...,107.433333,1.665333,106.283333,1.669032,2.245089,2.4,1.381215,108.6,2,-0.8
15,2013-07-01,111.0,111.2,7,2013,3,109.3,106.9,106.1,104.6,...,109.066667,2.059935,107.350000,2.302824,1.555352,1.7,0.999092,110.1,3,-0.2
16,2013-08-01,112.4,112.9,8,2013,3,111.0,109.3,106.9,105.3,...,110.900000,1.552417,108.533333,2.807609,1.261261,1.4,1.528777,111.2,4,-0.5
17,2013-09-01,113.7,114.3,9,2013,3,112.4,111.0,109.3,105.5,...,112.366667,1.350309,109.900000,3.023243,1.156584,1.3,1.240035,112.9,5,-0.6

In [42]:
df.to_csv('../data/processed/final_features.csv', index=False)